### PR TITLE
code updates from Zaher

### PR DESCRIPTION
**Pull request by falon3**
these updates are from Zaher's local code and hadn't been kept up to date on here

### CODE REVIEW

**Comment by cwant** [comment]
Hi @falon3  ,

I assume you are working with @hashisho  to integrate Gabriella's work?
From a superficial glance the work looks okay to me, but we should probably give you admin rights to the project so that you can push code directly.

Chris

**Review by cwant — APPROVED** [review]
Looks okay to me.

**Comment by falon3** [comment]
Yes illve adding some Plume visualizations to the project. I already forked
it anyway so it doesn't matter either way I could work off of either repo.

Thanks,

Falon

**Comment by hashisho** [comment]
Chris,

Thanks. I changed Falon’s access to Admin.

Zaher



*From:* Chris Want <notifications@github.com>
*Sent:* February 19, 2019 4:50 PM
*To:* Air-Quality-Engineering/oer_plotter <oer_plotter@noreply.github.com>
*Cc:* hashisho <hashisho@ualberta.ca>; Mention <mention@noreply.github.com>
*Subject:* Re: [Air-Quality-Engineering/oer_plotter] code updates from
Zaher (#6)



Hi @falon3 <https://github.com/falon3> ,

I assume you are working with @hashisho <https://github.com/hashisho> to
integrate Gabriella's work?
From a superficial glance the work looks okay to me, but we should probably
give you admin rights to the project so that you can push code directly.

Chris

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Air-Quality-Engineering/oer_plotter/pull/6#issuecomment-465359898>,
or mute the thread

**Pull request merged**
